// packages/web/src/components/carousel/sub-components/progress/index.tsx
import { cn } from '@/src/utils/shadcn';
import { CarouselProgressBarProps } from './interface';

export function CarouselProgressBar({
  progress,
  progressWrapperClassName,
}: CarouselProgressBarProps) {
  return (
    <div
      className={cn(
        'relative mt-10 h-1.5 max-w-[300px] overflow-hidden rounded-5 bg-accent-700 md:mx-auto md:h-2.5 lg:mt-20',
        progressWrapperClassName
      )}
    >
      <span
        className="absolute inset-0 z-[1] origin-left rounded-[inherit] bg-primary transition-[width] duration-500"
        style={{
          width: `${progress * 100}%`,
        }}
      ></span>
    </div>
  );
}

// packages/website/src/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { Progress as ProgressPrimitive } from 'bits-ui'
	import { cn } from '$lib/utils.js'

	type $$Props = ProgressPrimitive.Props

	let className: $$Props['class'] = undefined
	export let max: $$Props['max'] = 100
	export let value: $$Props['value'] = undefined
	export { className as class }
</script>

<ProgressPrimitive.Root
	class={cn(
		'relative h-2 w-full overflow-hidden rounded-full bg-primary/20',
		className
	)}
	{...$$restProps}
>
	<div
		class="h-full w-full flex-1 bg-primary transition-all"
		style={`transform: translateX(-${100 - (100 * (value ?? 0)) / (max ?? 1)}%)`}
	/>
</ProgressPrimitive.Root>
